--- #YAML:1.0
name:                Convert-Age
version:             0.03
abstract:            convert integer seconds into a "compact" form and back.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.35
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Chris Fedde <cfedde@cpan.org>
